theme: jekyll-theme-minimal
title: "Will Lockhart | Home"
logo: https://github.com/WSLockhart/Physics/blob/master/SolarSystem.jpg?raw=true
description: "I am a graduate student in high-energy astrophysics at the University of Arizona. 
My research is focused on neutron stars. I use computer simulations to calculate the radiation emitted by these stars 
(millisecond pulsars to be specific), and predict what that light should look like to our telescopes here on Earth. 
By comparing these predictions with observational data, we hope to put constraints on the size, magnetic field, 
and other fundamental properties of these near-inconceivable objects. 
Feel free to contact me at wlockhart@email.arizona.edu."
