theme: jekyll-theme-minimal
title: Will Lockhart Home
logo: https://github.com/WSLockhart/Physics/blob/master/SolarSystem.jpg
description: This site is currently a work in progress. Check back for updates

what's up with this?
