theme: jekyll-theme-minimal
title: "Will Lockhart"
logo: /images/SolarSystem.jpg
description: "I am a PhD student in high-energy astrophysics at the University of Arizona, and director of the 
first feature documentary on the game of Go. <br /> Feel free to contact me at wlockhart@email.arizona.edu."
