theme: jekyll-theme-minimal
title: "Will Lockhart"
logo: /images/SolarSystem.jpg
description: "I am a 3rd-year graduate student in astrophysics at the University of Arizona, and director of the 
first feature documentary on the game of Go. Feel free to contact me at wlockhart@email.arizona.edu."
