theme: jekyll-theme-minimal
title: "Will Lockhart | Home"
logo: https://github.com/WSLockhart/Physics/blob/master/SolarSystem.jpg?raw=true
description: "I am a 3rd-year graduate student in high-energy astrophysics at the University of Arizona. 
My research focuses on understanding the radiation mechanisms of millisecond pulsars. 

I also directed a documentary film, "The Surrounding Game", 
which is now available at www.surroundinggamemovie.com! Feel free to contact me at wlockhart@email.arizona.edu."
