theme: jekyll-theme-minimal
title: Will Lockhart | Home
logo: https://github.com/WSLockhart/Physics/blob/master/SolarSystem.jpg?raw=true
description: I am a 3rd-year graduate student in high-energy astrophysics at the University of Arizona. 

This site is currently a work in progress. Check back for updates
